### ISSUE TITLE
checkpoint server returns 404 not found

### ISSUE THREAD

**Issue by ZiangYan** [co60ca/EmotionNet2#7]
Is the server currently unavailable?

**Comment by co60ca** [comment]
Uh yeah, I needed that port for something else, I'll fix it right now

**Comment by co60ca** [comment]
Additionally, please do not rely on that URL staying the same. I might move it to another port in the near future. If you're just downloading by coming to this page and clicking the link or manually from a server that should be fine.

**Comment by co60ca** [comment]
I changed the port if it matters to you today. Please see the new port in the README.md :2222

**Comment by ZiangYan** [comment]
Thanks! It works for me now
